Fix test for world location navigation
The test never specified the document type for the link, so we never
tested the path of a `world_location` being present without any
`world_location_news` links.

Updating the test so the `document_type` is included, which allows us to
replicate an error we are currently seeing in production:

```
ActionView::Template::Error:
  undefined method `any?' for nil:NilClass
```