Fix conditional in related navigation helper
This fixes the following error, caused by attempting to call `any?` on
a nil value:

```
ActionView::Template::Error:
  undefined method `any?' for nil:NilClass
```